name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Rust
      run: cargo build --verbose

    - name: Run Rust tests
      run: cargo test --verbose
      
    - name: Install wasm-pack
      # uses: jetli/wasm-pack-action@f98777369a49686b132a9e8f0fdd59837bf3c3fd
      uses: jetli/wasm-pack-action@v0.3.0
    
    - name: Build rust-wasm
      run: |
        cd wasm
        wasm-pack build
        
    - name: Build webpack
      run: |
        cd wasm/www
        npm install
        ls ../pkg
        npm run build
